-define(HAL_RESOURCE(Links, Embeddeds, Properties), pera_hal:resource(Links, Embeddeds, Properties)).
-define(HAL_LINK(Name, Href, Properties), pera_hal:link(Name, Href, Properties)).
-define(HAL_EMBEDDED(Name, Resources), {Name, Resources}).
-define(HAL_PROPERTY(Name, Value), {property, Name, Value}).
-define(HAL_PROPERTY_OBJECT(Properties), {object, Properties}).
